/**
 * Created by luyongjie on 2016/11/16.
 */
export class PoRowData {
    "billNo":any;
    "companyUuid":any;
    "notes":any;
    "expectedArriveDate1":any;
    "expectedArriveDate2":any;
    "status":any;
    "tenantUuid":any;
    "type":any;
    "userDefine01":any;
    "userDefine02":any;
    "userDefine03":any;
    "userDefine04":any;
    "userDefine05":any;
    "userDefine06":any;
    "userDefine07":any;
    "userDefine08":any;
    "uuid":any;
    "version":number;
    "supplier":{
        "supplierCode":any;
        "supplierNameC":any;
        "supplierNameE":any;
        "supplierUuid":any;
    };
    "owner":{
        "ownerCode":any;
        "ownerNameC":any;
        "ownerNameE":any;
        "ownerUuid":any;
    };
    "whoCreate":{
        "name":any;
        "time":any;
        "uuid":any;
    };
    "whoEdit":{
        "name":any;
        "time":any;
        "uuid":any;
    };
    "details":[{
        "billLineNo":any;
        "billNo": any;
        "companyUuid": any;
        "lotAtt01":any;
        "lotAtt02":any;
        "lotAtt03":any;
        "lotAtt04":any;
        "lotAtt05":any;
        "lotAtt06":any;
        "lotAtt07":any;
        "lotAtt08":any;
        "lotAtt09":any;
        "lotAtt10":any;
        "lotAtt11":any;
        "lotAtt12":any;
        "notes":any;
        "orderedQty":number;
        "ordeedQtyStr":any;
        "owner":{
            "ownerCode":any;
            "ownerNameC":any;
            "ownerNameE":any;
            "ownerUuid":any
        };
        "price":number;
        "receivedQty":number;
        "receivedQtyStr":any;
        "receivedTime":any;
        "releasedQty":number;
        "releasedQtyStr":any;
        "sku":{
            "skuCode":any;
            "skuNameC":any;
            "skuNameE":any;
            "skuUuid":any
        };
        "skuPackage":{
            "packCode":any;
            "packQty":number;
            "packUOM":any;
            "packUuid":any
        };
        "status":any;
        "tenantUuid":any;
        "totalAmount":number;
        "totalGrossWeight":number;
        "totalNetWeight":number;
        "totalVolume":number;
        "userDefine01":any;
        "userDefine02":any;
        "userDefine03":any;
        "userDefine04":any;
        "userDefine05":any;
        "userDefine06":any;
        "userDefine07":any;
        "userDefine08":any;
        "uuid":any;
        "version":number;
        "whoCreate":{
            "name":any;
            "time":any;
            "uuid":any
        };
        "whoEdit":{
            "name":any;
            "time":any;
            "uuid":any
        }
    }]
}